//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalisisDGII.EL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASHCOLLECTION
    {
        public int CashCollectionID { get; set; }
        public int ConceptID { get; set; }
        public int SubConceptID { get; set; }
        public int CollectionYear { get; set; }
        public int MonthID { get; set; }
        public decimal AmountCollected { get; set; }
    
        public virtual CONCEPT CONCEPT { get; set; }
        public virtual MONTH MONTH { get; set; }
        public virtual SUBCONCEPT SUBCONCEPT { get; set; }
    }
}
