//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalisisDGII.EL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashCollectionView
    {
        public string Concept { get; set; }
        public string Sub_Concept { get; set; }
        public byte Year_Collected { get; set; }
        public string Month { get; set; }
        public decimal Amount { get; set; }
    }
}
