//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalisisDGII.EL.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DGIIEntities : DbContext
    {
        public DGIIEntities()
            : base("name=DGIIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CASHCOLLECTION> CASHCOLLECTIONs { get; set; }
        public virtual DbSet<CONCEPT> CONCEPTs { get; set; }
        public virtual DbSet<ISR> ISRs { get; set; }
        public virtual DbSet<MONTH> MONTHS { get; set; }
        public virtual DbSet<SUBCONCEPT> SUBCONCEPTs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<CashCollectionView> CashCollectionViews { get; set; }
        public virtual DbSet<VehicularParkView> VehicularParkViews { get; set; }
    }
}
