//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalisisDGII.EL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISR
    {
        public int FiscalYear { get; set; }
        public decimal MonthlyPayroll { get; set; }
        public decimal MonthlyRetention { get; set; }
    }
}
