//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalisisDGII.EL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicularParkView
    {
        public byte InscriptionYear { get; set; }
        public string MonthDesc { get; set; }
        public byte EntranceYear { get; set; }
        public string CarClassDescription { get; set; }
        public string CarTypeName { get; set; }
        public byte FabricationYear { get; set; }
        public string CarOriginDescription { get; set; }
        public string CarComapanyDescription { get; set; }
        public decimal Quantity { get; set; }
    }
}
